// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNXrFyx2-yq9TFQ3IAlZv3cWc7u2dFpzw',
    appId: '1:404283426933:web:741af2224b6a68724b103c',
    messagingSenderId: '404283426933',
    projectId: 'myapp-6b52b',
    authDomain: 'myapp-6b52b.firebaseapp.com',
    storageBucket: 'myapp-6b52b.appspot.com',
    measurementId: 'G-CXYJ7W2BZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBYHhT_7oHq9ybv2OpbjR7p9UbpqoxFXk',
    appId: '1:404283426933:android:57c6d78b8f733a5b4b103c',
    messagingSenderId: '404283426933',
    projectId: 'myapp-6b52b',
    storageBucket: 'myapp-6b52b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKSUOAo9_CEdoMssljezG633X0Ehg1_lE',
    appId: '1:404283426933:ios:c8b940f227cc53e34b103c',
    messagingSenderId: '404283426933',
    projectId: 'myapp-6b52b',
    storageBucket: 'myapp-6b52b.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKSUOAo9_CEdoMssljezG633X0Ehg1_lE',
    appId: '1:404283426933:ios:0db2361449e00dbe4b103c',
    messagingSenderId: '404283426933',
    projectId: 'myapp-6b52b',
    storageBucket: 'myapp-6b52b.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
